### ISSUE TITLE
Receive information about the user system

### ISSUE THREAD

**Issue by hendrikebbers** [AdoptOpenJDK/website-adoptium#21]
To provide a automatic download selection we need information about the user system

Which OS is the user using? (Win32, Win64, MacOS, Linux, ...)

**Comment by tresf** [comment]
For future-proof: https://github.com/WICG/ua-client-hints

Note, Safari isn't the best about reporting architecture, see also: https://github.com/WICG/ua-client-hints/issues/105#issuecomment-632375923

**Comment by miketaylr** [comment]
Hi there -- quick question: I added the `Sec-CH-UA-Bitness` header to the spec, which reports on the "bitness" of the platform / OS, but have been thinking it may be useful to know the bitness of the app (browser) in addition to the OS. 

For example, if you're running 32 bit Firefox or Chrome, on a 64 bit Windows. Is that useful for your use-case?

**Comment by aahlenst** [comment]
@miketaylr We're primarily interested in the OS and architecture of the host because we want to offer the right download. So when do I have a 32 bit browser on a 64 bit OS? I guess if the browser isn't ready for 64 bits. So I have a hard time to imagine when that info could be useful for our use case. But happy to be convinced otherwise.

**Comment by miketaylr** [comment]
Thanks -- that's helpful. No need to force a use case. :)
